---
title: "README"
author: "Martin HEIN (m#)"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output:
  html_document:
    fig_caption: yes
    fig_height: 6
    highlight: zenburn
    keep_md: yes
    number_sections: yes
    theme: journal
    toc: yes
  pdf_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 7
    highlight: zenburn
    number_sections: yes
    toc: yes
  word_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 7
    highlight: zenburn
    number_sections: yes
    toc: yes
---
# INTRODUCTION
This repository has been created to accommodate the project for the assignment of the [Coursera][coursera] class _[Developing Data Products][ddp]_, part of the _[Data Science Specialisation][dss]_.

# FILES
The project comprises of the following files.

| file | description | comment |
| -----: | :------- | :--------- |
| _global.R_ | constants used both by ui.R and server.R | |
| _help.Rmd_ | help text, formatted as R markdown, displayed by ui.R | menu item _**help**_ |
| _introduction.Rmd_ | introductory text, formatted as R markdown, displayed by ui.R | menu item _**introduction**_ |
| _README.md_ | this file, formatted as markdown | |
| _README.Rmd_ | this file, formatted as R markdown | |
| _server.R_ | Shiny app server applicaton part | |
| _Shiny Application and Reproducible Pitch.Rmd_ | project assignment, formated as R markdown, displayed by ui.R | menu item _**rationale**_ |
| _Shiny Application and Reproducible Pitch.Rpres_ | the _pitch_ presentation | |
| _Shiny Application and Reproducible Pitch.Rproj_ | RStudio project file | |
| _ui.R_ | Shiny app client/user interface application part | |

# USAGE
Open _**Shiny Application and Reproducible Pitch.Rproj**_ in _**RStudio**_, open & run either _**ui.R**_ or _**server.R**_, and follow the instructions displayed associated with menu item _**introduction**_.

# LINKS
* Corresponding [github repository][mygithub] (this page);
* Corresponding [Rpubs publication][myrpubs] (the published _pitch_ presentation);
* Corresponding [Shiny application][myshiny] (the web-based Shiny application at [shinyapps.io][shinyapps]).

-----
[coursera]: <https://www.coursera.org>
[ddp]: <https://www.coursera.org/learn/data-products/home/welcome>
[dss]: <https://www.coursera.org/specializations/jhu-data-science>
[shinyapps]: <http://www.shinyapps.io>
[mygithub]: <https://github.com/Sil68/dssshiny>
[myrpubs]: <https://rpubs.com/Sil68/dssshiny>
[myshiny]: <https://sil68-coursera.shinyapps.io/Shiny_Application_and_Reproducible_Pitch/>
